# -*- coding: utf-8 -*-
"""Spaceship Titanic Ensemble_.80453.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuoIqV5pZt2OUOZKoQBA-qGDh0x7AsNP
"""

import pandas as pd
import numpy as np
from scipy.stats.mstats import gmean

train=pd.read_csv('train.csv')
submission=pd.read_csv('sample_submission.csv')
y=train['Transported']

preds_cat=np.load('preds_cat.npy')
preds_xgb=np.load('preds_xgb.npy')
preds_pytorch=np.load('preds_pytorch.npy')
val_preds_cat=np.load('val_preds_cat.npy')
val_preds_xgb=np.load('val_preds_xgb.npy')
val_preds_pytorch=np.load('val_preds_pytorch.npy')

val_preds=0.5*val_preds_pytorch+0.3*val_preds_xgb + 0.2*val_preds_cat

from sklearn.metrics import f1_score

def to_labels(pos_probs, threshold):
	return (pos_probs >= threshold).astype('int')
 
thresholds = np.arange(0, 1, 0.001)
scores = [f1_score(y, to_labels(val_preds, t)) for t in thresholds]
ix = np.argmax(scores)
print('Threshold=%.3f, F-Score=%.5f' % (thresholds[ix], scores[ix]))

preds_xgb=gmean(preds_xgb, axis=1)
preds_cat=gmean(preds_cat, axis=1)

ensemble_preds=0.5*preds_pytorch+0.3*preds_xgb + 0.2*preds_cat

ensemble_preds=np.where(ensemble_preds<thresholds[ix], 0, 1)

ensemble_preds=ensemble_preds.astype('bool')

submission.head()

submission.drop('Transported', axis=1, inplace=True)

submission['Transported']=ensemble_preds

submission.head()

submission.to_csv('submission.csv', index=False)